package pl.perfectsource.kogito.rules;

unit Second;

import pl.perfectsource.kogito.ruleunit.RuleInput;
import pl.perfectsource.kogito.ruleunit.RuleOutput2;

import org.drools.ruleunits.api.DataSource;
import org.drools.ruleunits.api.DataStream;
import org.drools.ruleunits.api.RuleUnitData;

declare Second extends RuleUnitData
    input: DataStream<RuleInput> = DataSource.createStream();
    output: DataStream<RuleOutput2> = DataSource.createStream();
end

rule "Test2"
when
    /input [ test == "Hello" ];
then
    output.append(new RuleOutput2());
end

query Second
    out: /output
end
